### ISSUE TITLE
ERROR: Can't find a 'gtest/1.7.0@lasote/stable' package for the specified options and settings

### ISSUE THREAD

**Issue by sger** [lasote/conan-gtest#12]
Hello, 

I'm trying to install gtest but I'm getting the following output

`Requirements
    gtest/1.7.0@lasote/stable from conan.io
Packages
    gtest/1.7.0@lasote/stable:6930affda001dc28b1deb6ad58e56385dec517ad

gtest/1.7.0@lasote/stable: Installing package 6930affda001dc28b1deb6ad58e56385dec517ad
gtest/1.7.0@lasote/stable: Looking for package 6930affda001dc28b1deb6ad58e56385dec517ad in remote 'conan.io'
gtest/1.7.0@lasote/stable: WARN: Binary for 6930affda001dc28b1deb6ad58e56385dec517ad not in remote: Package not found!
ERROR: Can't find a 'gtest/1.7.0@lasote/stable' package for the specified options and settings

- Try to build from sources with "--build gtest" parameter
- If it fails, you could try to contact the package author  at 'http://github.com/lasote/conan-gtest', report your configuration and try to collaborate to support it.

Package configuration:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=8.0, os=Macos
- Options: shared=True`

I'm on OS X heres my conanfile.txt

`[requires]
gtest/1.7.0@lasote/stable

[options]
gtest:shared=True

[generators]
txt
cmake`

any ideas?

**Comment by lasote** [comment]
I've not apple-clang 8 binary packages uploaded yet. So you can use the "--build" option in the conan install command to build the binary yourself.

Thanks!
