### ISSUE TITLE
Compile error with gtest 1.7.x and msvc2012

### ISSUE THREAD

**Issue by tonka3000** [lasote/conan-gtest#19]
Hey,

there is an compiler error if i use gtest 1.7 and msvc2012. It seems that this is only a problem in this combination. Please can you add `_VARIADIC_MAX=10` define durring compile time of gtest 1.7.x in your recipe if msvc2012 (aka msvc11) is present, because this will fix the error.

[here](http://stackoverflow.com/questions/8274588/c2977-stdtuple-too-many-template-arguments-msvc11) you can see why this is required with msvc2012

Thanks in advance

**Comment by lasote** [comment]
Hi, Sorry for the long delay, I've added the definition for Visual Studio 11. Please update your recipe and try it, reopen the issue if it's not working I promise to answer quickly.
You can force update the recipe with `conan install -u`
