### ISSUE TITLE
Build fails with "undefined reference" 

### ISSUE THREAD

**Issue by massenz** [lasote/conan-gtest#23]
I have been trying to use the gtest/1.8.0 Conan package, but I am running into the "undefined reference" error and I seem unable to find out what causes it.

I have created a very simple demo project to demonstrate the error:
https://github.com/massenz/fail_conan

The README there provides more details, but the TL;DR version is that it seems that symbols defined in the `gtest.h` header are not found in the `libgtest.a` library.

I'm not sure whether this is a bug in the package definition or an issue on my system: any suggestions greatly appreciated.
(NOTE - I have been tried very hard to remove all other possible versions of `libgtest` from my system - I'm wondering, in fact, if anyone has ever actually tried to use this package and has been successful).

**Comment by lasote** [comment]
Hi, thanks for reporting. I'm looking at it. Will report ASAP

**Comment by lasote** [comment]
In your `conanfile.txt` you are specifying the shared gtest library, have you tried with the static?
It's working OK for me, I'm using Mac

**Comment by massenz** [comment]
Thanks for looking into it.
I thought I'd already tried that (that was, in fact, the first thing I suspected of being the issue) but I've tried it again, and it still doesn't work.

I am on Ubuntu 16.04, running Clang 3.6

I will try this out on MacOS too and report back.
(my very strong suspicion is that my system somehow has stashed a version of gtest 1.7 which I've been unable to track down... but I'm wondering if there is a way to tell cmake to only look in a given place or something).

**Comment by massenz** [comment]
ok - the "static" version totally works on MacOS - so there is definitely something wonky on my Ubuntu system.
Did you ever manage to try out the recipe on an Ubuntu system?
It would be good to know it does work there.

Also, mostly for my own curiosity, is there a way to build `gtest` as a dynamic lib too?

Again - so many thanks for making this available: for the libs where I can make it work, Conan is a major time-saver!

**Comment by lasote** [comment]
Hi again! Thanks, we are very glad you like Conan.

I've tried in Ubuntu with GCC and I was able to reproduce the error, the trick is to specify the `libstdc++11`, it seems it uses some symbols from that library.

Just run conan install with:

```
conan install . -s compiler=gcc -s compiler.libcxx=libstdc++11 
```

For the `clang` compiler should be the same, just choose `clang` instead `gcc`in `-s compiler`.
You can alter the global standard c++ library in your `~/.conan/conan.conf`or use conan profiles if it's more confortable for you: http://docs.conan.io/en/latest/mastering/profiles.html
You could have a profile just specifing the compiler.libcxx setting and use that profile in the conan install command.

Hope it helps!

**Comment by massenz** [comment]
oh, yeah, man!
that did it, solved the problem - not so much in the "simple demo" app, but in the much more interesting "serious app" :smile: https://github.com/massenz/distlib

Not to mention that there it also seems to have fixed weird multi-threading issues (that I was seeing in the tests, but not when running the code) - so, a true "win, win, win" :+1: 

The totally confusing part was that I was already using the `libstdc++` flag, but not the `11` variant... 

Again, I cannot thank you enough for jumping on this so quickly and not letting go of it!

**Comment by massenz** [comment]
BTW - would you like me to update the README for this project with these info?
Very happy to send a PR your way, if you'd like me to.

Thanks again.

**Comment by lasote** [comment]
That's great! :)
If you can make the PR I'll be happy :)
