### ISSUE TITLE
Project can't be linked with other one builded in MSVC 19 in Debug mode

### ISSUE THREAD

**Issue by JavierJF** [lasote/conan-gtest#28]
If you try to link against the project with another one compiled in MSVC in Debug configuration you get the following error:

error LNK2038: ... _ITERATOR_DEBUG_LEVEL': the value '0' doesn't match with the value '2' in ...

It looks like specifying the build_type=Debug in the conan installation does nothing to the configuration in which the project will be build.

**Comment by lasote** [comment]
Thanks, I'm taking a look

**Comment by lasote** [comment]
Yes, It seems I introduced an error and I was no wrapping the CMake with the conan injected settings. Currently I'm working on improving this recipe to be able to push it to the new conan-center repository, so thanks so much.

**Comment by JavierJF** [comment]
Great! You are welcome! You are doing an awesome work porting all this packages to Conan. Thanks you!

**Comment by JavierJF** [comment]
Hi! Sorry I have been trying to use the package again and I have run into two issues:

1.  First reported issue hasn't disappeared.
2.  When trying to compile the current project I get the following python error.

> ERROR: gtest/1.8.0@javjarfer/testing: Error in package_info() method, line 92
>         if self.settings.compiler == "Visual Studio" and self.settings.compiler.version >= 15:
>         TypeError: '>=' not supported between instances of 'SettingsItem' and 'int'

Thanks you.

**Comment by lasote** [comment]
Hi,

I fixed the comparison and pushed to the branch **release/1.8.0**.
About the debug/release missmatch, I cannot reproduce it, It looks ok. 
Can you tell me some steps to reproduce it? Thanks

**Comment by nicolastagliani** [comment]
I think the problem with your build settings is that in the end the debug package will end up being compiled with the MD flag instead of MDd.
These are the settings after a debug compilation of your packaged gtest library.

[settings]
    arch=x86_64
    build_type=**Debug**
    compiler=Visual Studio
    compiler.runtime=**MD**
    compiler.version=14
    os=Windows

In my project I'm building (trying to) a dll with some gtest associated and I'm relying both on gtest_main and gtest library. Unfortunately the main executable is not building due to MD/MDd inconsistencies.

The options I provided to build gtest are: 
[options]
    cygwin_msvc=False
    fpic=False
    include_pdbs=False
    no_gmock=True
    no_main=False
    shared=False

**Comment by nicolastagliani** [comment]
Found a solution for the compilation issue.
My suggestion is to explicitly specify the compiler runtime while building with visual studio.
```
conan install . -s build_type=Debug -s compiler.runtime=MDd
```
Documentation says that in conan >0.26 the Debug build_type implies MDd and Release implies MD (which is fine) but it didn't work for me.
