### ISSUE TITLE
Missing package?

### ISSUE THREAD

**Issue by dptd** [lasote/conan-gtest#40]
Hello there. I wanted to play around with conan.io today and download gtest using it. It looks like this package was removed from the conan.io.

`$ conan search "gtest"`
`There are no packages matching the 'gtest' pattern`

Can you please clarify the gtest package situation? Thanks!

**Comment by lasote** [comment]
You have to specify the remote to search:

`conan search "gtest" -r conan-center` 
> gtest/1.7.0@bincrafters/stable

The gtest package is now maintained by the Bincrafters community: 

https://github.com/bincrafters

**Comment by dptd** [comment]
Ouch! I feel so dumb now. Thanks a lot!

**Comment by lasote** [comment]
No problem!!! We are here to help. Glad you use Conan! :)

**Comment by vkotovv** [comment]
@lasote Can you please state in the Readme that this repo is deprecated and this package is now maintained by Bincrafters? I think it makes sense to provide a link to this repo: https://github.com/bincrafters/conan-gtest
