### ISSUE TITLE
cannot build from source

### ISSUE THREAD

**Issue by pellet** [lasote/conan-gtest#7]
`ERROR: gtest/1.7.0@lasote/stable: Error in source() method, line 24
	download(url, zip_name)
	Error 404 downloading file https://googletest.googlecode.com/files/gtest-1.7.0.zip`
I think google removed the source archive once they released gtest 1.8.0, googlecode was always on it's way out.  Unfortunately this means if the binary is not available this dependency cannot be built.
this link looks good https://github.com/google/googletest/archive/release-1.7.0.zip

**Comment by lasote** [comment]
Thanks for the PR, great job

**Comment by pellet** [comment]
cheers mate
